### ISSUE TITLE
GGUF but from standard checkpoint folder

### ISSUE THREAD

**Issue by ronowe** [city96/ComfyUI-GGUF#127]
Hi, I have an issue that for example on openart.ai you can't download models to Unet folder. Is it possible to use GGUF but with a standard checkpoint folder on ComfyUI. It would be great. Best regards, Daniel

**Comment by city96** [comment]
Hi. The current gguf models only contain the unet part, so it wouldn't make sense to have them in the checkpoint folder. It might be worth asking the openart.ai people to add native support for other download locations.

I guess one (janky) thing you could do is add the checkpoint folder as a unet folder in `extra_model_paths.yaml` lol.

```yaml
unet_remap:
    base_path: "C:\\ComfyUI\\models"
    unet: checkpoints
```
